name: AWS Integration Request

on:
  issues:
    labels: [aws-integration-request]

jobs:
  process:
    name: Process AWS Integration Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Issue Forms Body Parser
        id: parse-issue
        uses: zentered/issue-forms-body-parser@v2.2.0
      - name: Update configuration file
        run: |
          AWS_ACCOUNT_ID=$(echo '${{ steps.parse-issue.outputs.data }}' | jq -r '.["aws-account-id"].text')
          echo "New account ID env: $AWS_ACCOUNT_ID"
          cd infra
          jq --arg id "$AWS_ACCOUNT_ID" '.account_ids += [$id]' config.json > temp.json && mv temp.json config.json
          cat config.json
