name: Check Exercise Links

on:
  workflow_dispatch:



permissions:
  contents: read
  issues: write

jobs:
  get-repos:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.set-matrix.outputs.repos }}
    steps:
      - name: Get all repositories in github.com/skills with topic skills-course and not archived
        id: get-repos
        uses: actions/github-script@v7
        with:
          script: |
            const org = 'skills';
            const topic = 'skills-course';

            const { data: repos } = await github.rest.search.repos({
              q: `org:${org} topic:${topic} archived:false`,
              per_page: 100
            });

            // Only return full_name for each repo
            return repos.items.map(repo => repo.full_name);
      - name: Set matrix output
        id: set-matrix
        run: |
          echo "repos=$(echo '${{ steps.get-repos.outputs.result }}' | jq -c)" >> $GITHUB_OUTPUT

  link-check:
    needs: get-repos
    name: Lychee Link Check (${{ matrix.repo }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.get-repos.outputs.repos) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
      - name: Check Links with Lychee
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args:  --verbose --no-progress './**/*.md' './**/*.html' --include '^https://github.com/user-attachments/'
          fail: false

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Failures (${{ matrix.repo }})
          content-filepath: ./lychee/out.md
          assignees: |
            FidelusAleksander
