name: AI Issue Responder
on:
  issues:
    types: [opened, edited, reopened, closed]

permissions:
  issues: write
  models: read

jobs:
  respond-to-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: FidelusAleksander/ask-ai
          ref: v1
          token: ${{ secrets.PAT }}

      - name: Generate AI response
        id: ai-response
        uses: ./
        with:
          prompt: |
            Respond to this GitHub issue. Your response should be ready to post as a comment.

            AUTHOR: ${{ github.event.issue.user.login }}
            TITLE: ${{ github.event.issue.title }}
            DESCRIPTION: ${{ github.event.issue.body }}

            - Thank the user for their issue
            - For bug reports: request any missing information (reproduction steps, expected/actual behavior, environment)
            - For feature requests: acknowledge the idea and ask for use cases if not provided
            - Sign as "AI Assistant"
            - Use a friendly, appreciative tone

      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## 👋 Hello there!

            ${{ steps.ai-response.outputs.text }}

            _This is an automated response from our AI assistant. A human maintainer will review your issue soon._
