name: Check PR Title
on:
  pull_request:
    types: [opened]

permissions:
  models: read
  pull-requests: write

jobs:
  respond-to-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: FidelusAleksander/prompt
          ref: main
          token: ${{ secrets.PAT }}

      - name: Prompt
        id: prompt
        uses: ./
        with:
          prompt: |
            Modify this PR title to match conventional commit styling:

            ${{ github.event.pull_request.title }}

      - name: Update PR Title
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: ${{ steps.prompt.outputs.text }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --title "$PR_TITLE" --repo ${{ github.repository }}
