name: test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run script
        run: |
          echo "test self-hosted runner"
