name: Step 4

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  issues: write

jobs:

  start_exercise:
    name: Restart Exercise
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Get response templates
        run: gh issue reopen https://github.com/FidelusAleksander/github-playground/issues/76
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finish_exercise:
    name: Finish Exercise
    needs: [start_exercise]
    uses: skills/exercise-toolkit/.github/workflows/finish-exercise.yml@add-socials-section
    with:
      issue-url: https://github.com/FidelusAleksander/github-playground/issues/76

