name: test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test-secret:
    runs-on: self-hosted
    if: ${{ secrets.MY_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - name: Run script
        run: |
          echo ${{ secrets.MY_SECRET }}

  test-var:
    runs-on: self-hosted
    if: ${{ vars.MY_VAR }}
    steps:
      - uses: actions/checkout@v4
      - name: Run script
        run: |
          echo ${{ vars.MY_VAR }}
