name: Ask AI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  models: read

jobs:
  test-action-prompt:
    name: Test Action with Prompt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: FidelusAleksander/ask-ai
          ref: v1
          token: ${{ secrets.PAT }}
      - uses: ./
        with:
          prompt: "What is the meaning of life?"
