name: test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build application
    steps:
      - run: echo "hello world"
  deploy-dev:
    needs: [build]
    runs-on: ubuntu-latest
    name: Deploy to dev
    environment: dev
    steps:
      - run: echo "hello world"
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    name: Deploy to ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "hello world"
