name: test

on:
  workflow_dispatch:
  push:
    branches:
      - extract-secrets

jobs:
  test:
    runs-on: self-hosted
    steps:
      - run: echo ${{ secrets.MY_SECRET }}
      - run: echo ${{ secrets.MY_SECRET }} > my_secret.txt
