name: Semantic Release
permissions:
  id-token: write
  contents: write
on:
  push:
    branches:
      - main
      - feat/**
      - fix/**


jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Add repository content to workflow
        uses: actions/checkout@v4
      - name: Dump GitHub event context
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT"
      - name: Overwrite README
        run: echo "123" > README.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "README.md"
          message: "Bump 1"
          default_author: github_actions

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Add repository content to workflow
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Dump GitHub event context
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT"
      - name: Overwrite README
        run: echo "321" > README.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "README.md"
          message: "Bump 1"
          default_author: github_actions

        

