name: test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      some_string:
        description: 'string'
        required: false
        type: string
      some_number:
        description: 'number'
        type: number
        required: false
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run script
        run: |
          echo "test default input number ${{ inputs.some_string }}"
          echo "test default input string ${{ inputs.some_number }}"
