name: Translate README

on:
  push:
    paths:
      - 'README.md'

permissions:
  contents: write
  pull-requests: write
  models: read

jobs:
  translate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ['spanish', 'french', 'german', 'chinese', 'polish']
        include:
          - language: 'spanish'
            file: 'README.es.md'
          - language: 'french'
            file: 'README.fr.md'
          - language: 'german'
            file: 'README.de.md'
          - language: 'chinese'
            file: 'README.zh.md'
          - language: 'polish'
            file: 'README.pl.md'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: docs/update-readme-translations

      - uses: actions/checkout@v4
        with:
          repository: FidelusAleksander/ai-translate
          path: ai-translate
          ref: v1

      - name: Translate README
        uses: ./ai-translate
        id: translate
        with:
          text-file: 'README.md'
          target-language: ${{ matrix.language }}
          custom-instructions: "Keep technical terms and code in English."

      - name: Save translation
        run: echo "${{ steps.translate.outputs.translated-text }}" > docs/${{ matrix.file }}

      - name: Commit translation
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs/${{ matrix.file }}'
          message: 'docs: update ${{ matrix.language }} translation of README'
          default_author: github_actions

  create-pr:
    needs: translate
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "docs: update translations of README"
          title: "docs: update translations of README"
          body: |
            This PR updates all translations of the README:

            Changes were automatically generated using the AI Translate action.
          branch: "docs/update-readme-translations"
          delete-branch: true
          labels: |
            documentation
