name: Translate README

on:
  push:
  workflow_dispatch:

env:
  BRANCH_NAME: docs/update-readme-translations

permissions:
  contents: write
  pull-requests: write
  models: read

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create branch if not exists
        run: |
          git fetch origin
          git checkout -B ${{ env.BRANCH_NAME }}
          git push -f origin ${{ env.BRANCH_NAME }}

  translate:
    needs: create-branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ["spanish", "french", "german", "chinese", "polish"]
        include:
          - language: "spanish"
            file: "README.es.md"
          - language: "french"
            file: "README.fr.md"
          - language: "german"
            file: "README.de.md"
          - language: "chinese"
            file: "README.zh.md"
          - language: "polish"
            file: "README.pl.md"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}

      - uses: actions/checkout@v4
        with:
          repository: FidelusAleksander/ai-translate
          path: ai-translate
          ref: v1
          token: ${{ secrets.PAT }}

      - name: Translate README
        uses: ./ai-translate
        id: translate
        with:
          text-file: "README.md"
          target-language: ${{ matrix.language }}
          custom-instructions: "Keep technical terms in English. Don't translate code blocks"

      - name: Save translation
        run: echo "${{ env.TRANSLATED_TEXT }}" > docs/${{ matrix.file }}
        env:
          TRANSLATED_TEXT: ${{ steps.translate.outputs.translated-text }}

      - name: Commit translation
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs/${{ matrix.file }}"
          message: "docs: update ${{ matrix.language }} translation of README"
          default_author: github_actions

  create-pr:
    needs: translate
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "docs: update translations of README"
          title: "docs: update translations of README"
          body: |
            This PR updates all translations of the README:

            Changes were automatically generated using the AI Translate action.
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: true
          labels: |
            documentation
